# ------------------------------------------------
# wpa_suppliacant P2P Basic Configuration
# Both devices share these settings
# __PLACEHOLDER__s are filled by setup.sh
# ------------------------------------------------

ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

# P2P
p2p_disabled=0
p2p_listen_channel=6
p2p_oper_channel=__CHANNEL__
p2p_oper_reg_class=__REG_CLASS__

# WPS - paswordless triggering
config_methods=push_button
wps_cred_processing=1

# Persistent group - first connection is saved, subsequent boots connect directly
persistent_reconnect=1

# Power efficiency
uapsd=1 # Unscheduled Automatic Power Save Delivery - power saving mode for Wi-Fi
p2p_go_max_inactivity=300 # Maximum inactivity time (in seconds) for the P2P Group Owner before it considers the group inactive and may disconnect clients to save power.

country=TR