# ------------------------------------------
# wpa_supplicant - CLIENT (Station) Configuration
# mode=0 → standard STA, connects to host AP
# No P2P overhead, works on all supported devices
# ------------------------------------------
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

p2p_disabled=1

country=TR

network={
    ssid="__SSID__"
    psk="__PSK__"
    mode=0
    key_mgmt=WPA-PSK
    proto=RSN
    pairwise=CCMP
    auth_alg=OPEN
    frequency=__FREQ__
    disabled=0
}
