# ------------------------------------------------------
# wpa_supplicant - P2P HOST(Group Owner) Configuration
# ------------------------------------------------------
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

p2p_disabled=0
p2p_go_intent=15    # Always become a Group Owner
p2p_listen_channel=6
p2p_oper_channel=__CHANNEL__
p2p_oper_reg_class=__REG_CLASS__

config_methods=push_button
wps_cred_processing=1
persistent_reconnect=1

# Persistent Group
# disabled=2 - this is a P2P group defination, not remove
network={
    ssid="__SSID__"
    psk="__PSK__"
    mode=3
    disabled=2
    key_mgmt=WPA-PSK
    proto=RSN
    pairwise=CCMP
    auth_alg=OPEN
    frequency=__FREQ__
}