# ------------------------------------------------------
# wpa_supplicant - HOST (Access Point) Configuration
# mode=2 → direct AP on physical interface
# No P2P-GO, no virtual interfaces, no extra overhead
# ------------------------------------------------------
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

p2p_disabled=1

country=TR

network={
    ssid="__SSID__"
    psk="__PSK__"
    mode=2
    key_mgmt=WPA-PSK
    proto=RSN
    pairwise=CCMP
    auth_alg=OPEN
    frequency=__FREQ__
    disabled=0
}
