# ------------------------------------------
# wpa_supplicant - CLIENT P2P Configuration
# ------------------------------------------
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

p2p_disabled=0
p2p_go_intent=0     # Never become a Group Owner for battery saving
p2p_listen_channel=6
p2p_oper_channel=__CHANNEL__
p2p_oper_reg_class=__REG_CLASS__

config_methods=push_button
wps_cred_processing=1
persistent_reconnect=1
uapsd=1
p2p_go_max_inactivity=300
p2p_no_group_iface=0
country=TR

device_name=__DEVICE_NAME__
manufacturer=__MANUFACTURER__
device_type=__DEVICE_TYPE__

# Persistenr Group
network={
    ssid="__SSID__"
    psk="__PSK__"
    mode=0
    disabled=2
    key_mgmt=WPA-PSK
    proto=RSN
    pairwise=CCMP
    auth_alg=OPEN
    frequency=__FREQ__
}